

SELECT * FROM PATIENTS;


select *, DOD, DOB,
YEAR(DOD) - YEAR(DOB)
    - (DATE_FORMAT(DOD, '%m%d') < DATE_FORMAT(DOB, '%m%d')) as AGE
from PATIENTS;


SELECT * 
FROM prescriptions 
WHERE FORM_VAL_DISP REGEXP '^[0-9]+\\.?[0-9]*$'; 


WITH FIRST_ADMISSION_TIME AS (
SELECT 
    P.SUBJECT_ID, P.DOB, P.GENDER, 
    MIN (A.ADMITTIME) AS FIRST_ADMITTIME
FROM PATIENTS P
INNER JOIN ADMISSIONS A
ON P.SUBJECT_ID = A.SUBJECT_ID
GROUP BY P.SUBJECT_ID, P.DOB, P.GENDER, A.HADM_ID
ORDER BY A.HADM_ID, P.SUBJECT_ID
),
AGE AS (
SELECT 
    SUBJECT_ID,  DOB, GENDER, FIRST_ADMITTIME, 
    AGE(FIRST_ADMITTIME, DOB) 
        AS FIRST_ADMIT_AGE, 
    CASE
       WHEN AGE(FIRST_ADMITTIME, DOB) > '89 YEARS'
            THEN '>89'
        WHEN AGE(FIRST_ADMITTIME, DOB) >= '15 YEARS'
            THEN 'ADULT'
        WHEN AGE(FIRST_ADMITTIME, DOB) <= '1  YEAR'
            THEN 'NEONATE'
        ELSE 'MIDDLE'
        END AS AGE_GROUP
FROM FIRST_ADMISSION_TIME
ORDER BY SUBJECT_ID
)
SELECT *
FROM AGE;